<?php

namespace Database\Seeders;

use App\Models\Employe;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmployeSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nip' => '196511281991031002',
                'name' => 'Ir. RAZILU, M.Si.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 17,
                'tmt_pangkat' => '2018-12-03',
                'jabatan_id' => 27,
                'tmt_jabatan' => '2020-03-08',
                'tmt_pensiun' => null,
                'eselon_id' => 1,
                'unit_id' => null,
            ],
            [
                'nip' => '196211251989031002',
                'name' => 'BUDI, S.H.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2016-04-01',
                'jabatan_id' => 25,
                'tmt_jabatan' => '2022-11-03',
                'tmt_pensiun' => null,
                'eselon_id' => 2,
                'unit_id' => null,
            ],
            [
                'nip' => '197110171995031001',
                'name' => 'LILIK SUJANDI, Bc.I.P., S.I.P., M.Si.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2022-10-01',
                'jabatan_id' => 28,
                'tmt_jabatan' => '2023-01-02',
                'tmt_pensiun' => null,
                'eselon_id' => 3,
                'unit_id' => null,
            ],
            [
                'nip' => '196310011991032001',
                'name' => 'LULUK RATNANINGTYAS, S.H., M.Hum.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2017-04-01',
                'jabatan_id' => 32,
                'tmt_jabatan' => '2022-03-10',
                'tmt_pensiun' => null,
                'eselon_id' => 7,
                'unit_id' => null,
            ],
            [
                'nip' => '196404251990011001',
                'name' => 'Drs. MARASIDIN, Bc.I.P., M.H.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2021-04-01',
                'jabatan_id' => 31,
                'tmt_jabatan' => '2022-03-10',
                'tmt_pensiun' => null,
                'eselon_id' => 6,
                'unit_id' => null,
            ],
            [
                'nip' => '196403111994032007',
                'name' => 'YAYAH MARIANI, S.H., M.H.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2019-10-01',
                'jabatan_id' => 68,
                'tmt_jabatan' => '2023-01-02',
                'tmt_pensiun' => null,
                'eselon_id' => 1,
                'unit_id' => null,
            ],
            [
                'nip' => '196911281997031001',
                'name' => 'BAMBANG SETYABUDI, S.H.,M.H.',
                'gender' => 'LAKI LAKI',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2023-04-01',
                'jabatan_id' => 30,
                'tmt_jabatan' => '2023-01-02',
                'tmt_pensiun' => null,
                'eselon_id' => 5,
                'unit_id' => null,
            ],
            [
                'nip' => '197004301991031001',
                'name' => 'IWAN SANTOSO, S.H., M.Si.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 16,
                'tmt_pangkat' => '2023-04-01',
                'jabatan_id' => 29,
                'tmt_jabatan' => '2022-03-10',
                'tmt_pensiun' => null,
                'eselon_id' => 4,
                'unit_id' => null,
            ],
            [
                'nip' => '197010091998032001',
                'name' => 'RANI OCTARIANI, S.H., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2020-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-01-01',
                'tmt_pensiun' => null,
                'eselon_id' => 6,
                'unit_id' => null,
            ],
            [
                'nip' => '197006061998032001',
                'name' => 'ERBATA SRI MULIATINI, S.H., M.M.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2021-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-08-17',
                'tmt_pensiun' => null,
                'eselon_id' => 7,
                'unit_id' => null,
            ],
            [
                'nip' => '197012181999031002',
                'name' => 'ANDRIYANTO W. P, S.H., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2021-10-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-08-17',
                'tmt_pensiun' => null,
                'eselon_id' => 5,
                'unit_id' => null,
            ],
            [
                'nip' => '196406211993031001',
                'name' => 'AMINULLAH NOOR PAKPAHAN, S.H., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2022-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2023-04-03',
                'tmt_pensiun' => null,
                'eselon_id' => 3,
                'unit_id' => null,
            ],
            [
                'nip' => '196710271993031001',
                'name' => 'ICHSANUDIN EKO SAPUTRO, S.H., M.Si.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2023-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-08-17',
                'tmt_pensiun' => null,
                'eselon_id' => 5,
                'unit_id' => null,
            ],
            [
                'nip' => '196507201994031001',
                'name' => 'QOLBIN SALIM, S.E., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2023-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2023-04-03',
                'tmt_pensiun' => null,
                'eselon_id' => 5,
                'unit_id' => null,
            ],
            [
                'nip' => '197508291999032001',
                'name' => 'TITUT SULISTYANINGSIH, S.E.,M.Si',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2022-10-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-08-17',
                'tmt_pensiun' => null,
                'eselon_id' => 6,
                'unit_id' => null,
            ],
            [
                'nip' => '197107231997031001',
                'name' => 'AGUNG NATANAEL, S.H., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2022-10-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-08-17',
                'tmt_pensiun' => null,
                'eselon_id' => 6,
                'unit_id' => null,
            ],
            [
                'nip' => '197003271998032001',
                'name' => 'AMI AMATUNISSA, S.H., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 15,
                'tmt_pangkat' => '2022-10-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2022-10-03',
                'tmt_pensiun' => null,
                'eselon_id' => 3,
                'unit_id' => null,
            ],
            [
                'nip' => '197203051999031007',
                'name' => 'DR. JOKO MARTANTO, S.E, M.SI.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 14,
                'tmt_pangkat' => '2017-10-01',
                'jabatan_id' => 37,
                'tmt_jabatan' => '2019-02-27',
                'tmt_pensiun' => null,
                'eselon_id' => 1,
                'unit_id' => null,
            ],
            [
                'nip' => '196905061998031001',
                'name' => 'ERIE WIJAYA, S.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 14,
                'tmt_pangkat' => '2020-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2022-10-03',
                'tmt_pensiun' => null,
                'eselon_id' => 4,
                'unit_id' => null,
            ],
            [
                'nip' => '196405151985031016',
                'name' => 'SARWADI, S.H., M.H.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 14,
                'tmt_pangkat' => '2020-04-01',
                'jabatan_id' => 12,
                'tmt_jabatan' => '2021-12-31',
                'tmt_pensiun' => null,
                'eselon_id' => 1,
                'unit_id' => null,
            ],
            [
                'nip' => '197410112001121001',
                'name' => 'Dr. INDRA JAYA ALI, S.E,.M.Si',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 14,
                'tmt_pangkat' => '2021-04-01',
                'jabatan_id' => 19,
                'tmt_jabatan' => '2021-08-17',
                'tmt_pensiun' => null,
                'eselon_id' => 2,
                'unit_id' => null,
            ],
            [
                'nip' => '196906071992032001',
                'name' => 'EEM NURMANAH, S.Sos., M.Si.',
                'gender' => 'PEREMPUAN',
                'email' => null,
                'phone_number' => null,
                'is_wa' => null,
                'pangkat_id' => 14,
                'tmt_pangkat' => '2021-10-01',
                'jabatan_id' => 7,
                'tmt_jabatan' => '2021-01-01',
                'tmt_pensiun' => null,
                'eselon_id' => 1,
                'unit_id' => null,
            ],
            // Tambahkan data pegawai lainnya di sini
        ];

        foreach ($data as $pegawaiData) {
            Employe::create($pegawaiData);
        }
    }
}
